"""Thin Anthropic client wrapper. Scoring/pitch calls force a structured tool-use
response so callers get validated JSON, not freeform text to parse."""
from __future__ import annotations

import json
import os
from typing import Optional

DEFAULT_MODEL = "claude-sonnet-5"


class LLMError(RuntimeError):
    pass


class ClaudeClient:
    def __init__(self, api_key: Optional[str] = None, model: str = DEFAULT_MODEL):
        api_key = api_key or os.environ.get("ANTHROPIC_API_KEY")
        if not api_key:
            raise LLMError(
                "ANTHROPIC_API_KEY is not set. Export it, put it in .env, or run with --llm mock."
            )
        import anthropic  # imported lazily so `--llm mock` never requires the package

        self._client = anthropic.Anthropic(api_key=api_key)
        self.model = model

    def structured_call(
        self,
        system: str,
        user_prompt: str,
        tool_name: str,
        tool_description: str,
        input_schema: dict,
        max_tokens: int = 1024,
    ) -> dict:
        response = self._client.messages.create(
            model=self.model,
            max_tokens=max_tokens,
            system=system,
            tools=[
                {
                    "name": tool_name,
                    "description": tool_description,
                    "input_schema": input_schema,
                }
            ],
            tool_choice={"type": "tool", "name": tool_name},
            messages=[{"role": "user", "content": user_prompt}],
        )
        for block in response.content:
            if block.type == "tool_use" and block.name == tool_name:
                return block.input
        raise LLMError(f"Model did not return a {tool_name} tool call")


class MockLLMClient:
    """Deterministic, offline stand-in for ClaudeClient — lets the pipeline be
    exercised end-to-end without an API key. Uses simple keyword-overlap
    heuristics; not a substitute for real semantic scoring."""

    def structured_call(
        self,
        system: str,
        user_prompt: str,
        tool_name: str,
        tool_description: str,
        input_schema: dict,
        max_tokens: int = 1024,
    ) -> dict:
        if tool_name == "submit_score":
            return self._mock_score(user_prompt)
        if tool_name == "submit_pitch":
            return self._mock_pitch(user_prompt)
        if tool_name == "submit_briefing":
            return self._mock_briefing(user_prompt)
        raise LLMError(f"MockLLMClient does not know how to handle tool {tool_name}")

    @staticmethod
    def _mock_score(prompt: str) -> dict:
        # Search only the query-specific portion of the prompt (summary onward) —
        # searching the whole prompt would also match the profile's own
        # KEYWORDS_INCLUDE list against itself and always "find" every keyword.
        query_text = prompt.split("QUERY SUMMARY:", 1)[-1].lower()
        overlap = 0
        matched = None
        try:
            keywords_section = prompt.split("KEYWORDS_INCLUDE:", 1)[1].split("\n", 1)[0]
            candidates = [k.strip().lower() for k in keywords_section.split(",") if k.strip()]
        except IndexError:
            candidates = []
        for kw in candidates:
            if kw and kw in query_text:
                overlap += 1
                matched = matched or kw
        topical = 30 if overlap else 0
        return {
            "topical_fit": topical,
            "source_type_fit": 10 if overlap else 0,
            "answerability": 10 if overlap else 5,
            "outlet_value": 8,
            "matched_signal": matched,
            "rationale": (
                f"[mock] keyword overlap on '{matched}'" if matched else "[mock] no keyword overlap found"
            ),
        }

    @staticmethod
    def _mock_pitch(prompt: str) -> dict:
        return {
            "pitch_text": (
                "[MOCK PITCH — set ANTHROPIC_API_KEY for a real draft]\n\n"
                "This is a placeholder pitch generated by the offline mock LLM client. "
                "[NEEDS SPOKESPERSON INPUT: real answers to the journalist's questions]"
            )
        }

    @staticmethod
    def _mock_briefing(prompt: str) -> dict:
        return {
            "briefing_note": (
                "[MOCK BRIEFING NOTE — set ANTHROPIC_API_KEY for a real briefing]\n\n"
                "Questions, angle and talking points would be generated here by the real "
                "model. This query has 'No AI Pitches Considered' set, so a human must "
                "write the actual pitch from this briefing."
            )
        }


def build_llm_client(mode: str, api_key: Optional[str] = None, model: str = DEFAULT_MODEL):
    if mode == "mock":
        return MockLLMClient()
    if mode == "claude":
        return ClaudeClient(api_key=api_key, model=model)
    raise ValueError(f"Unknown --llm mode: {mode!r} (expected 'claude' or 'mock')")
